name: New Github Release

on:
  push:
    branches:
      - master
    paths:
      - '**/*.py'
      - '.github/workflows/release.yaml'

jobs:
  release:
    runs-on: ubuntu-latest
    name: Release
    if: github.repository_owner == 'l13t'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 23.0.2
          extra_plugins: |
            @semantic-release/changelog@6.0.3
            @semantic-release/git@10.0.1
            conventional-changelog-conventionalcommits@7.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GH_SECRET }}
